"""Generate and validate the local environment used by workflow listeners."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from pathlib import PurePath
from urllib.parse import urlparse


_AGENT_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
_HOST_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$")


def default_config_path() -> Path:
    """Return the per-user listener environment path."""
    root = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return root / "agent-bus" / "listener.env"


def shell_quote(value: str) -> str:
    """Quote a literal for POSIX shells without exposing it to evaluation."""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def token_variable(agent: str) -> str:
    """Map an Agent Bus role to the matching AWF token variable."""
    if not _AGENT_RE.fullmatch(agent):
        raise ValueError(
            "agent must start with a letter and contain only letters, digits, _ or -"
        )
    return f"AWF_{agent.upper().replace('-', '_')}_TOKEN"


def network_host(url: str) -> str:
    """Extract the host that must bypass proxies and may need network warm-up."""
    parsed = urlparse(url)
    host = parsed.hostname
    if parsed.scheme not in {"http", "https"} or not host:
        raise ValueError("url must be an http(s) URL with a hostname")
    if not _HOST_RE.fullmatch(host):
        raise ValueError("url hostname contains unsupported characters")
    return host


def source_path(path: PurePath) -> str:
    """Render a path for a POSIX shell, including Git Bash on Windows."""
    value = path.as_posix()
    match = re.fullmatch(r"([A-Za-z]):(/.*)", value)
    if match:
        return f"/{match.group(1).lower()}{match.group(2)}"
    return value


def render_listener_env(
    *,
    agent: str,
    url: str,
    awf_env: Path,
    repo_dir: Path,
    script_dir: Path,
    warmup_command: str = "tailscale",
) -> str:
    """Render a sourceable environment file without copying token values."""
    token_var = token_variable(agent)
    host = network_host(url)
    values = {
        "url": shell_quote(url.rstrip("/")),
        "agent": shell_quote(agent),
        "awf_env": shell_quote(source_path(awf_env)),
        "repo_dir": shell_quote(repo_dir.as_posix()),
        "script_dir": shell_quote(script_dir.as_posix()),
        "host": shell_quote(host),
        "warmup": shell_quote(warmup_command),
    }
    return f"""# Generated by agent-bus init. Local-only; do not commit.
set -a
. {values["awf_env"]}
set +a
export AGENT_BUS_URL={values["url"]}
export AGENT_BUS_AGENT={values["agent"]}
export AGENT_BUS_TOKEN=\"${{{token_var}:?{token_var} is required}}\"
export AWF_REPO_DIR={values["repo_dir"]}
export AWF_SCRIPT_DIR={values["script_dir"]}
export OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS=true
export AGENT_BUS_NETWORK_HOST={values["host"]}
export AGENT_BUS_WARMUP_COMMAND={values["warmup"]}
case ",${{NO_PROXY:-}}," in
  *,\"$AGENT_BUS_NETWORK_HOST\",*) ;;
  *) export NO_PROXY=\"${{NO_PROXY:+${{NO_PROXY}},}}${{AGENT_BUS_NETWORK_HOST}}\" ;;
esac
export no_proxy=\"$NO_PROXY\"
"""


def write_listener_env(path: Path, content: str, *, force: bool = False) -> None:
    """Atomically write a private listener environment file."""
    path = path.expanduser()
    if path.exists() and not force:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.chmod(0o600)
        temporary.replace(path)
        path.chmod(0o600)
    finally:
        if temporary.exists():
            temporary.unlink()


def listener_environment_issues(env: dict[str, str] | None = None) -> list[str]:
    """Return actionable problems in the current listener environment."""
    current = os.environ if env is None else env
    issues = []
    required = (
        "AGENT_BUS_TOKEN",
        "AGENT_BUS_AGENT",
        "AGENT_BUS_NETWORK_HOST",
        "AGENT_BUS_WARMUP_COMMAND",
        "AWF_REPO_DIR",
        "AWF_SCRIPT_DIR",
    )
    for name in required:
        if not current.get(name):
            issues.append(f"{name} is not set")
    for name in ("AWF_REPO_DIR", "AWF_SCRIPT_DIR"):
        value = current.get(name)
        if value and not Path(value).is_dir():
            issues.append(f"{name} is not a directory")
    if current.get("OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS") != "true":
        issues.append("OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS must be true")
    host = current.get("AGENT_BUS_NETWORK_HOST")
    bypass = {item.strip() for item in current.get("NO_PROXY", "").split(",")}
    if host and host not in bypass:
        issues.append("AGENT_BUS_NETWORK_HOST is missing from NO_PROXY")
    command = current.get("AGENT_BUS_WARMUP_COMMAND")
    if command and shutil.which(command) is None:
        issues.append("AGENT_BUS_WARMUP_COMMAND is not executable")
    return issues


def warm_network_path(env: dict[str, str] | None = None) -> str | None:
    """Warm the configured private-network path without invoking a shell."""
    current = os.environ if env is None else env
    command = current.get("AGENT_BUS_WARMUP_COMMAND", "")
    host = current.get("AGENT_BUS_NETWORK_HOST", "")
    if not command or not host:
        return "network warm-up is not configured"
    for name, argv in (
        ("status", [command, "status"]),
        (
            "ping",
            [command, "ping", "--until-direct=false", "--c=1", host],
        ),
    ):
        try:
            completed = subprocess.run(
                argv,
                capture_output=True,
                text=True,
                timeout=20,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return f"network {name} failed: {type(exc).__name__}"
        if completed.returncode != 0:
            return f"network {name} exited {completed.returncode}"
    return None
