"""Generate and validate the local environment used by workflow listeners."""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlparse


_AGENT_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")


def default_config_path() -> Path:
    """Return the per-user listener environment path."""
    root = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return root / "agent-bus" / "listener.env"


def shell_quote(value: str) -> str:
    """Quote a literal for POSIX shells without exposing it to evaluation."""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def token_variable(agent: str) -> str:
    """Map an Agent Bus role to the matching AWF token variable."""
    if not _AGENT_RE.fullmatch(agent):
        raise ValueError(
            "agent must start with a letter and contain only letters, digits, _ or -"
        )
    return f"AWF_{agent.upper().replace('-', '_')}_TOKEN"


def network_host(url: str) -> str:
    """Extract the host that must bypass proxies and may need network warm-up."""
    host = urlparse(url).hostname
    if not host:
        raise ValueError("url must include a hostname")
    return host


def render_listener_env(
    *,
    agent: str,
    url: str,
    awf_env: Path,
    repo_dir: Path,
    script_dir: Path,
    warmup_command: str = "tailscale",
) -> str:
    """Render a sourceable environment file without copying token values."""
    token_var = token_variable(agent)
    host = network_host(url)
    values = {
        "url": shell_quote(url.rstrip("/")),
        "agent": shell_quote(agent),
        "awf_env": shell_quote(str(awf_env)),
        "repo_dir": shell_quote(str(repo_dir)),
        "script_dir": shell_quote(str(script_dir)),
        "host": shell_quote(host),
        "warmup": shell_quote(warmup_command),
    }
    return f"""# Generated by agent-bus init. Local-only; do not commit.
set -a
. {values["awf_env"]}
set +a
export AGENT_BUS_URL={values["url"]}
export AGENT_BUS_AGENT={values["agent"]}
export AGENT_BUS_TOKEN=\"${{{token_var}:?{token_var} is required}}\"
export AWF_REPO_DIR={values["repo_dir"]}
export AWF_SCRIPT_DIR={values["script_dir"]}
export OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS=true
export AGENT_BUS_NETWORK_HOST={values["host"]}
export AGENT_BUS_WARMUP_COMMAND={values["warmup"]}
case ",${{NO_PROXY:-}}," in
  *,{host},*) ;;
  *) export NO_PROXY=\"${{NO_PROXY:+${{NO_PROXY}},}}{host}\" ;;
esac
export no_proxy=\"$NO_PROXY\"
"""


def write_listener_env(path: Path, content: str, *, force: bool = False) -> None:
    """Atomically write a private listener environment file."""
    path = path.expanduser()
    if path.exists() and not force:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.chmod(0o600)
        temporary.replace(path)
        path.chmod(0o600)
    finally:
        if temporary.exists():
            temporary.unlink()


def listener_environment_issues(env: dict[str, str] | None = None) -> list[str]:
    """Return actionable problems in the current listener environment."""
    current = os.environ if env is None else env
    issues = []
    required = ("AGENT_BUS_TOKEN", "AGENT_BUS_AGENT", "AWF_REPO_DIR", "AWF_SCRIPT_DIR")
    for name in required:
        if not current.get(name):
            issues.append(f"{name} is not set")
    for name in ("AWF_REPO_DIR", "AWF_SCRIPT_DIR"):
        value = current.get(name)
        if value and not Path(value).is_dir():
            issues.append(f"{name} is not a directory")
    if current.get("OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS") != "true":
        issues.append("OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS must be true")
    host = current.get("AGENT_BUS_NETWORK_HOST")
    bypass = {item.strip() for item in current.get("NO_PROXY", "").split(",")}
    if host and host not in bypass:
        issues.append("AGENT_BUS_NETWORK_HOST is missing from NO_PROXY")
    return issues
