#!/usr/bin/env bash
# Install Agent Bus Server with Docker Compose.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${AGENT_BUS_DOCKER_ENV_FILE:-$ROOT_DIR/.env}"
GENERATED_TOKENS=false
ARCHITECT_TOKEN=""
CODER_TOKEN=""

compose() {
    docker compose \
        --project-directory "$ROOT_DIR" \
        --file "$ROOT_DIR/compose.yaml" \
        --env-file "$ENV_FILE" \
        "$@"
}

generate_token() {
    local token
    token="$(LC_ALL=C od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
    if [[ ! "$token" =~ ^[0-9a-f]{64}$ ]]; then
        echo "Failed to generate a secure token." >&2
        return 1
    fi
    printf '%s' "$token"
}

create_environment() {
    local env_dir temporary_env
    env_dir="$(dirname "$ENV_FILE")"
    umask 077
    mkdir -p "$env_dir"

    if [ -L "$ENV_FILE" ]; then
        echo "Refusing to replace symlinked environment file: $ENV_FILE" >&2
        return 1
    fi

    ARCHITECT_TOKEN="$(generate_token)"
    CODER_TOKEN="$(generate_token)"
    temporary_env="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
    trap 'rm -f "$temporary_env"' RETURN
    {
        echo "# Generated by scripts/install-docker.sh. Keep this file private."
        echo "AGENT_BUS_AGENT_TOKENS=architect=$ARCHITECT_TOKEN,coder=$CODER_TOKEN"
    } > "$temporary_env"
    chmod 600 "$temporary_env"
    mv "$temporary_env" "$ENV_FILE"
    trap - RETURN
    GENERATED_TOKENS=true
}

validate_environment() {
    local token_mapping
    token_mapping="$(
        sed -n 's/^AGENT_BUS_AGENT_TOKENS=//p' "$ENV_FILE" |
            tail -n 1
    )"
    if [ -z "${token_mapping//[[:space:]]/}" ]; then
        echo "AGENT_BUS_AGENT_TOKENS is missing or blank in $ENV_FILE." >&2
        echo "Add a per-agent token mapping or remove the file and rerun the installer." >&2
        return 1
    fi
    chmod 600 "$ENV_FILE"
}

wait_for_health() {
    local attempt container_id state
    container_id="$(compose ps -q agent-bus)"
    if [ -z "$container_id" ]; then
        echo "Agent Bus container was not created." >&2
        compose logs --tail 50 agent-bus >&2 || true
        return 1
    fi

    for ((attempt = 1; attempt <= 30; attempt++)); do
        state="$(
            docker inspect \
                --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' \
                "$container_id" 2>/dev/null || true
        )"
        case "$state" in
            healthy)
                return 0
                ;;
            exited | dead)
                echo "Agent Bus container stopped before becoming healthy." >&2
                compose logs --tail 50 agent-bus >&2 || true
                return 1
                ;;
        esac
        sleep 1
    done

    echo "Agent Bus did not become healthy within 30 seconds." >&2
    compose logs --tail 50 agent-bus >&2 || true
    return 1
}

echo "==> Checking Docker Compose"
if ! command -v docker >/dev/null 2>&1; then
    echo "Docker is required. Install Docker Engine with the Compose v2 plugin." >&2
    exit 1
fi
docker compose version >/dev/null

if [ -e "$ENV_FILE" ]; then
    echo "==> Reusing protected configuration at $ENV_FILE"
    validate_environment
else
    echo "==> Generating per-agent tokens in $ENV_FILE"
    create_environment
fi

echo "==> Validating Compose configuration"
compose config --quiet

echo "==> Building and starting Agent Bus"
compose up -d --build

echo "==> Waiting for container health"
wait_for_health

echo
echo "Agent Bus container is healthy."
echo "Configuration: $ENV_FILE"
echo "Data: persistent Compose volume mounted at /data"
if [ "$ENV_FILE" = "$ROOT_DIR/.env" ]; then
    echo "Logs: docker compose logs -f agent-bus"
else
    echo "Logs: docker compose --env-file $ENV_FILE logs -f agent-bus"
fi

if [ "$GENERATED_TOKENS" = true ]; then
    echo
    echo "Save these tokens now. They are shown only on first installation:"
    echo "  Architect token: $ARCHITECT_TOKEN"
    echo "  Coder token:     $CODER_TOKEN"
fi
